### ISSUE TITLE
"Unhandled exception in script" when attempting to open

### ISSUE THREAD

**Issue by EternityEngine** [Jonius7/SteamUI-OldGlory#114]
After updating to 5.16, when I try to run `old_glory.exe`, it pops up an error window:

![error](https://github.com/user-attachments/assets/370a5a69-a26e-4eea-ac50-05e0a4af78ae)

The traceback:
```
Traceback (most recent call last):
  File "git\__init__.py", line 296, in <module>
  File "git\__init__.py", line 287, in refresh
  File "git\cmd.py", line 631, in refresh
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "old_glory.py", line 16, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "manager.py", line 21, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "old_glory.py", line 17, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "backend.py", line 25, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "git\__init__.py", line 298, in <module>
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
```

When I hit _Close_, the window closes and the program fails to run. I don't have git installed, which seems to be the cause of the error. I don't think that's meant to be required. This also happens if I run a fresh copy of the program.

**Comment by Jonius7** [comment]
This is an oversight by me, added a new feature that is still unreleased on the GUI which requires GitPython. I should aim to fix it soon.
