### ISSUE TITLE
GNU/Linux Issue (python3-tk)

### ISSUE THREAD

**Issue by gmod64bit** [Jonius7/SteamUI-OldGlory#69]
```
[shane@archlinux SteamUI-OldGlory-master]$ ./aids.sh
Traceback (most recent call last):
  File "/home/shane/Downloads/SteamUI-OldGlory-master/old_glory.py", line 1, in <module>
    import tkinter as tk
  File "/usr/lib/python3.10/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory

```

Any ideas how I can fix her up?

This was following this 
https://github.com/Jonius7/SteamUI-OldGlory/wiki/Linux

**Comment by Jonius7** [comment]
You may need to install `tk` seperately something like: `sudo apt-get install python3-tk`
