### ISSUE TITLE
libraryroot.js not found // No module named 'six'

### ISSUE THREAD

**Issue by Potato95** [Jonius7/SteamUI-OldGlory#73]
Latest Steam version (non-Beta) and latest OldGlory version.

```
Running js_tweaker
Copying file library.js from Steam\steamui...
Opening library.beaut.js, generating beautified JS...
libraryroot.js not found
~~~~~~~~~~
Traceback (most recent call last):
  File "js_tweaker.py", line 91, in beautify_js
  File "jsbeautifier\__init__.py", line 86, in beautify_file
  File "jsbeautifier\cli\__init__.py", line 122, in process_file
  File "jsbeautifier\__init__.py", line 81, in beautify
  File "jsbeautifier\javascript\beautifier.py", line 142, in __init__
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "jsbeautifier\javascript\acorn.py", line 17, in <module>
ModuleNotFoundError: No module named 'six'
None
~~~~~~~~~~
```

**Comment by Jonius7** [comment]
Fixed in [5.10.6](https://github.com/Jonius7/SteamUI-OldGlory/releases/tag/Release_5.10.6)
