### ISSUE TITLE
Check for Updates broken?

### ISSUE THREAD

**Issue by Potato95** [Jonius7/SteamUI-OldGlory#76]
Latest version of OldGlory upon execution, whether on user/admin permission.

```
Loaded JSON data. (old_glory_data.json)
Loaded CSS Options. (variables.css)
Loaded JS Tweaks. (fixes.txt)
You are up to date. Release 5.10.6
Checking for small updates...
Unable to get hash of file: themes/Acrylic Theme
~~~~~~~~~~~~~~~~~~~~
Traceback (most recent call last):
  File "backend.py", line 295, in get_file_hash
PermissionError: [Errno 13] Permission denied: 'themes/Acrylic Theme'
~~~~~~~~~~~~~~~~~~~~
New Version | themes/Acrylic Theme
Unable to get hash of file: themes/Crisp Cut
~~~~~~~~~~~~~~~~~~~~
Traceback (most recent call last):
  File "backend.py", line 295, in get_file_hash
PermissionError: [Errno 13] Permission denied: 'themes/Crisp Cut'
~~~~~~~~~~~~~~~~~~~~
New Version | themes/Crisp Cut
Unable to get hash of file: themes/Dark Library
~~~~~~~~~~~~~~~~~~~~
Traceback (most recent call last):
  File "backend.py", line 295, in get_file_hash
PermissionError: [Errno 13] Permission denied: 'themes/Dark Library'
~~~~~~~~~~~~~~~~~~~~
New Version | themes/Dark Library
Unable to get hash of file: themes/OG-Steam-Library
~~~~~~~~~~~~~~~~~~~~
Traceback (most recent call last):
  File "backend.py", line 295, in get_file_hash
PermissionError: [Errno 13] Permission denied: 'themes/OG-Steam-Library'
~~~~~~~~~~~~~~~~~~~~
New Version | themes/OG-Steam-Library
Unable to get hash of file: themes/Pure [Light]
~~~~~~~~~~~~~~~~~~~~
Traceback (most recent call last):
  File "backend.py", line 295, in get_file_hash
PermissionError: [Errno 13] Permission denied: 'themes/Pure [Light]'
~~~~~~~~~~~~~~~~~~~~
New Version | themes/Pure [Light]
New Version | themes/config.css.original
Unable to get hash of file: themes/steam-library
~~~~~~~~~~~~~~~~~~~~
Traceback (most recent call last):
  File "backend.py", line 295, in get_file_hash
PermissionError: [Errno 13] Permission denied: 'themes/steam-library'
~~~~~~~~~~~~~~~~~~~~
New Version | themes/steam-library
```

**Comment by Jonius7** [comment]
Yeah there is an issue with updating the `themes` files, as seen in #74 
Still working on a fix

**Comment by Potato95** [comment]
OldGlory asks for update upon execution and after update is done doesn't return any errors.

To be fair, all themes had to be updated but not all of them received any updates recently. Also, restoring a backup of the theme folder before this update and asking to check for updates doesn't return any (as if the files never needed to be updated), might be something worth to check out. 

Original issue fixed nonetheless.

```
Loaded JSON data. (old_glory_data.json)
Loaded CSS Options. (variables.css)
Loaded JS Tweaks. (fixes.txt)
You are up to date. Release 5.10.7
Checking for small updates...
Done.

```
